import type { Metadata } from "next";
import { Mona_Sans } from "next/font/google";
import "@/styles/globals.css";
import React from "react";
import QueryProvider from "@/utils/queryProvider";
import { Footer, Header } from "@/components";
import { Box } from "@mui/material";
import SnackbarClient from "@/modules/common/SnackBar/SnackBarClient";

const lato = Mona_Sans({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Geo Cars Rent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <QueryProvider>
          <Header />
          <Box
            sx={{
              maxWidth: "1200px",
              margin: "auto",
              width: "100%",
            }}
          >
            {children}
            <SnackbarClient />
          </Box>
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
